name: Deploy with Maven

on:
  push:
    branches: [ "actiontest" ]
  pull_request:
    branches: [ "actiontest" ]
permissions:
  actions: write
  repository-projects: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Set up JDK 8
#       uses: actions/setup-java@v3
#       with:
#         java-version: '8'
#         distribution: 'liberica'
#         cache: maven
        
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with: # running setup-java again overwrites the settings.xml
        distribution: 'liberica'
        java-version: '8'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_KEY }} # Value of the GPG private key to import
        gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Build with Maven
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo ${OSSRH_USERNAME}
        cat /home/runner/.m2/settings.xml
        mvn -B clean package gpg:sign deploy -P release
